[package]
name = "catch22"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
pyo3 = "0.23.3"
rayon = "1.10.0"
rustfft = "6.2.0"

[profile.release]
lto = true
codegen-units = 1

[build-dependencies]
bindgen = "0.70.1"
cc = "1.1.36"


